name: packaging

on:
  push:
    branches:
      - main
      - release

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Assign version for main
        if: contains(github.ref, 'main')
        run:
          npm config set git-tag-version false
          npm version prerelease --preid=dev
      - name: Package VS code extension
        run:
          npm install
          npm run package
      - name: Archive vsix file
        uses: actions/upload-artifact@v2
        with:
          name: darkpetrol-extension
          path: ./*.vsix
