name: Publish to Marketplace

on:
  workflow_run:
    workflows: [Release]
    types:
      - completed

jobs:
  package:
    runs-on: ubuntu-latest
    outputs:
      vsixPath: ${{ steps.package-vsix.outputs.vsixPath }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: version
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if new version was released 
        run: |
          ls -la
          if [[ -f .NOVERSION ]]; then gh run cancel ${{ github.run_id }}; fi
          if [[ -f .NEWVERSION ]]; then echo "RELEASE_VERSION=$(cat .NEWVERSION | tr -d '[blank]')" >> $GITHUB_ENV; fi
      - name: Check out latest tag
        uses: actions/checkout@v4
        with:
          ref: $RELEASE_VERSION   
          fetch-depth: 10
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Assign version as in tag
        run: |
          npm config set git-tag-version false
          npm version $RELEASE_VERSION
      - name: Package VSIX
        id: package-vsix
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: stub
          dryRun: true
      - name: Upload Extension Package as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: darkpetrol-extension
          path: ${{ steps.package-vsix.outputs.vsixPath }}

  publish:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Download vsix from package
        uses: actions/download-artifact@v3
        with:
          name: darkpetrol-extension
      - uses: actions/checkout@v4
      - run: npm i
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSX_PAT }}
          extensionFile: ${{ needs.package.outputs.vsixPath }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ needs.package.outputs.vsixPath }}
