name: Publish to Marketplace

on:
  workflow_run:
    workflows: [Release]
    types:
      - completed

jobs:
  package:
    runs-on: ubuntu-latest
    outputs:
      vsixPath: ${{ steps.package-vsix.outputs.vsixPath }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: version
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if new version was released 
        run: |
          ls -la
          if [[ -f .NOVERSION ]]; then exit 1; fi
      - name: Get latest tag
        id: latestrelease
        run: |
          echo "::set-output name=releasetag::$(git describe --abbrev=0 --tags)"
      - name: tagcheckout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.latestrelease.outputs.releasetag }}         
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Assign version as in tag
        run: |
          npm config set git-tag-version false
          npm version $RELEASE_VERSION
      - name: Package VSIX
        id: package-vsix
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: stub
          dryRun: true
      - name: Upload Extension Package as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: darkpetrol-extension
          path: ${{ steps.package-vsix.outputs.vsixPath }}

  publish:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Download vsix from package
        uses: actions/download-artifact@v3
        with:
          name: darkpetrol-extension
      - uses: actions/checkout@v3
      - run: npm i
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSX_PAT }}
          extensionFile: ${{ needs.package.outputs.vsixPath }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ needs.package.outputs.vsixPath }}
